# Generated by Django 5.1.6 on 2025-03-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='process',
            field=models.TextField(blank=True, null=True),
        ),
    ]
